apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-voting
  annotations: {}
spec:
  ingressClassName: nginx
  rules:
  - host: velpoc-rke2-cluster-vel.atix-training.de
    http:
      paths:
      - path: /voting
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-result
  annotations: {}
spec:
  ingressClassName: nginx
  rules:
  - host: velpoc-rke2-cluster-vel.atix-training.de
    http:
      paths:
      - path: /result
        pathType: Prefix
        backend:
          service:
            name: result
            port:
              number: 5001  